spring:

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

server:
  ssl:
    key-store: /home/ubuntu/best-robbins/br-ssl.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
