name: ktlint

on: [pull_request]
jobs:
  ktlint:
    name: Check Code Quality by ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run ktlint
        run: ./gradlew ktlintCheck --no-daemon